from __future__ import annotations

from .models import ToolDefinition, ToolRiskLevel
from .registry import ToolRegistry, get_tool_registry


PLACEHOLDER_TOOLS: tuple[ToolDefinition, ...] = (
    ToolDefinition(
        tool_name="tool.claude.complete",
        connector_name="claude",
        action="complete",
        description="Openclaw primary executor — Claude AI for governed operator command execution.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("claude", "anthropic", "llm", "read_only", "agent_sync", "openclaw"),
        capability_metadata={
            "phase": "openclaw",
            "external_execution": True,
            "provider": "anthropic",
            "network_scope": "anthropic_only",
        },
        timeout_seconds=45,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="tool.openai.complete",
        connector_name="openai",
        action="complete",
        description="Bounded read-only OpenAI completion for governed research and analysis output.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("openai", "llm", "read_only", "agent_sync"),
        capability_metadata={
            "phase": "50",
            "external_execution": True,
            "provider": "openai",
            "network_scope": "openai_only",
        },
        timeout_seconds=30,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="system.echo",
        connector_name="system",
        action="echo",
        description="Structural placeholder tool for policy and registry validation only.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=False,
        tags=("internal", "placeholder"),
        capability_metadata={"phase": "7a", "external_execution": False},
        audit_category="tool.placeholder",
    ),
    ToolDefinition(
        tool_name="system.health_read",
        connector_name="system",
        action="health_read",
        description="Structural placeholder tool for future safe health-read requests.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=False,
        tags=("internal", "health", "placeholder"),
        capability_metadata={"phase": "7a", "external_execution": False},
        timeout_seconds=5,
        audit_category="tool.placeholder",
    ),
    ToolDefinition(
        tool_name="search.web_search",
        connector_name="search",
        action="web_search",
        description="Bounded read-only web search through the governed search connector.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=False,
        tags=("search", "connector", "read_only"),
        capability_metadata={"phase": "27", "external_execution": True},
        timeout_seconds=8,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.workflow.list",
        connector_name="n8n",
        action="workflow.list",
        description="List all n8n workflows.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("n8n", "automation", "read_only"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.workflow.create",
        connector_name="n8n",
        action="workflow.create",
        description="Create a new n8n workflow.",
        risk_level=ToolRiskLevel.medium,
        read_only=False,
        enabled_by_default=True,
        tags=("n8n", "automation", "write"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=20,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.workflow.activate",
        connector_name="n8n",
        action="workflow.activate",
        description="Activate an n8n workflow.",
        risk_level=ToolRiskLevel.medium,
        read_only=False,
        enabled_by_default=True,
        tags=("n8n", "automation", "write"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.workflow.execute",
        connector_name="n8n",
        action="workflow.execute",
        description="Trigger execution of an n8n workflow.",
        risk_level=ToolRiskLevel.medium,
        read_only=False,
        enabled_by_default=True,
        tags=("n8n", "automation", "execute"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=30,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.workflow.get",
        connector_name="n8n",
        action="workflow.get",
        description="Get details of an n8n workflow.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("n8n", "automation", "read_only"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.workflow.deactivate",
        connector_name="n8n",
        action="workflow.deactivate",
        description="Deactivate an n8n workflow.",
        risk_level=ToolRiskLevel.medium,
        read_only=False,
        enabled_by_default=True,
        tags=("n8n", "automation", "write"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.execution.list",
        connector_name="n8n",
        action="execution.list",
        description="List recent n8n workflow executions.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("n8n", "automation", "read_only"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="n8n.execution.get",
        connector_name="n8n",
        action="execution.get",
        description="Get details of a specific n8n execution.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("n8n", "automation", "read_only"),
        capability_metadata={"external_execution": True, "provider": "n8n"},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    # ── MEXC Exchange Tools ──────────────────────────────────────────────────
    ToolDefinition(
        tool_name="mexc.account.balance",
        connector_name="mexc",
        action="account.balance",
        description="Get current MEXC wallet balances (non-zero assets only).",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "trading"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=10,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.account.info",
        connector_name="mexc",
        action="account.info",
        description="Get MEXC account info including permissions and account type.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "trading"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=10,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.market.ticker",
        connector_name="mexc",
        action="market.ticker",
        description="Get current market price for a trading symbol on MEXC.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "market_data"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=8,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.market.orderbook",
        connector_name="mexc",
        action="market.orderbook",
        description="Get order book depth for a MEXC trading symbol.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "market_data"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=8,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.market.klines",
        connector_name="mexc",
        action="market.klines",
        description="Get OHLCV candlestick data for a MEXC symbol and interval.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "market_data"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=10,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.order.place",
        connector_name="mexc",
        action="order.place",
        description="Place a buy or sell order on MEXC. ALWAYS requires operator approval.",
        risk_level=ToolRiskLevel.high,
        read_only=False,
        enabled_by_default=True,
        tags=("mexc", "exchange", "write", "trading", "high_stakes"),
        capability_metadata={"external_execution": True, "provider": "mexc", "requires_approval": True},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.order.cancel",
        connector_name="mexc",
        action="order.cancel",
        description="Cancel an open order on MEXC. ALWAYS requires operator approval.",
        risk_level=ToolRiskLevel.high,
        read_only=False,
        enabled_by_default=True,
        tags=("mexc", "exchange", "write", "trading", "high_stakes"),
        capability_metadata={"external_execution": True, "provider": "mexc", "requires_approval": True},
        timeout_seconds=15,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.order.get",
        connector_name="mexc",
        action="order.get",
        description="Get status and details of a specific MEXC order.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "trading"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=10,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.order.list_open",
        connector_name="mexc",
        action="order.list_open",
        description="List all open orders on MEXC.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "trading"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=10,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.order.list_history",
        connector_name="mexc",
        action="order.list_history",
        description="Get order history for a MEXC trading symbol.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "trading"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=10,
        audit_category="tool.connector",
    ),
    ToolDefinition(
        tool_name="mexc.position.list",
        connector_name="mexc",
        action="position.list",
        description="List open futures positions on MEXC.",
        risk_level=ToolRiskLevel.low,
        read_only=True,
        enabled_by_default=True,
        tags=("mexc", "exchange", "read_only", "trading", "futures"),
        capability_metadata={"external_execution": True, "provider": "mexc"},
        timeout_seconds=10,
        audit_category="tool.connector",
    ),
)


def register_placeholder_tools(registry: ToolRegistry | None = None) -> ToolRegistry:
    target = registry or get_tool_registry()
    for tool in PLACEHOLDER_TOOLS:
        if not target.has_tool(tool.tool_name):
            target.register_tool(tool)
    return target

